apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-role-binding
subjects:
  - kind: ServiceAccount
    name: admin-sa
roleRef:
  kind: Role
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
