apiVersion: apps/v1
kind: Deployment
metadata:
  name: nft-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nft-app
  template:
    metadata:
      labels:
        app: nft-app
    spec:
      containers:
        - name: nft-app
          image: public.ecr.aws/q2x5y1y2/krishna1423:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nft-app-service
spec:
  type: NodePort
  ports:
    - port: 80 # The service port
      targetPort: 3000 # The container port
      nodePort: 30007
  selector:
    app: nft-app
