apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-role-binding
subjects:
  - kind: ServiceAccount
    name: user-sa
roleRef:
  kind: Role
  name: user-role
  apiGroup: rbac.authorization.k8s.io
